### ISSUE TITLE
[Enhancment] Compatibility with REI and zoom percentage

### ISSUE THREAD

**Issue by DoctorMeta** [Siphalor/big-items-duh#1]
Could you also show big items for REI? The same way Item Zoom shows for JEI.
And if possible could you make a config with the percentage of zoom?

**Comment by Siphalor** [comment]
That both sounds pretty doable :)

It's still funny to see that what started out as a joke is actually getting used ^^

**Comment by DoctorMeta** [comment]
Well, I like the feature. I think it's cool and sort of useful. Even if it's a joke I would love those 2 things implemented if you have the time. Thank you in advance!
